

services:
  redis-master:
    image: bitnami/redis:7.4.0-debian-12-r2
    container_name: redis
    ports: ["6379:6379"]
    volumes: ["./redis:/data"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - turl
  redis-sentinel:
    image: bitnami/redis-sentinel:7.4.0-debian-12-r1
    container_name: redis-sentinel
    ports: ["26379:26379"]
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - turl
networks:
  turl:
    driver: bridge
