

services:
  redis:
    image: bitnami/redis:7.4.0-debian-12-r2
    container_name: redis
    ports: ["6379:6379"]
    volumes: ["./redis:/data"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - turl
  backend:
    image: backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
        NODE_ENV: local
        PORT: "3000"
    ports:
      - "3000:3000"
networks:
  turl:
    driver: bridge
