

services:

  backend:
    container_name: backend
    depends_on:
      migrations:
        condition: service_started
    entrypoint: sh -c "npm i && npm run start:dev"
    environment:
      NODE_ENV: development
    image: node:22
    ports: ["3001:3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api"]
    working_dir: "/app"
    volumes: ["./backend:/app", "/app/node_modules"]

