name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [backend]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys
    needs: [builds]
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.deployer.yml@main
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      triggers: ('backend/')
      params:
        --set global.secrets.persist=false



  results:
    name: PR Results
    needs: [builds, deploys]
    if: always() && (!failure()) && (!cancelled())
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Success!"
